const fs = require("fs");
const path = require("path");

const pkgPath = path.resolve(__dirname, "..", "package.json");
const outPath = path.resolve(__dirname, "..", "src", "version.ts");

function main() {
  let pkg = { version: "0.0.0" };
  try {
    pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
  } catch (e) {
    // ignore
  }
  // Try to obtain the current git short commit hash. If not available, fall back to timestamp.
  let shortHash = null;
  try {
    const { execSync } = require("child_process");
    shortHash = String(
      execSync("git rev-parse --short HEAD", { encoding: "utf8" }),
    ).trim();
  } catch (e) {
    // ignore - git may not be available in some environments
  }
  const fallback = new Date().toISOString();
  const meta = shortHash || fallback.replace(/[:.]/g, "-");
  // Create a version string that includes package version and commit short-hash (build metadata)
  const version = `${pkg.version}+${meta}`;
  const content = `// This file is auto-generated by scripts/write-version.cjs\nexport const VERSION = ${JSON.stringify(
    version,
  )};\n`;
  fs.writeFileSync(outPath, content, "utf8");
  console.log("Wrote version to", outPath);
}

main();
