const fs = require("fs");
const path = require("path");

const pkgPath = path.resolve(__dirname, "..", "package.json");
const outPath = path.resolve(__dirname, "..", "src", "version.ts");

function main() {
  let pkg = { version: "0.0.0" };
  try {
    pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
  } catch (e) {
    // ignore
  }
  const buildTime = new Date().toISOString();
  // Create a version string that includes package version and timestamp to force updates
  const version = `${pkg.version}-${buildTime}`;
  const content = `// This file is auto-generated by scripts/write-version.js\nexport const VERSION = ${JSON.stringify(
    version,
  )};\nexport const BUILD_TIME = ${JSON.stringify(buildTime)};\n`;
  fs.writeFileSync(outPath, content, "utf8");
  console.log("Wrote version to", outPath);
}

main();
